### ISSUE TITLE
HHTabBarView by default overlaps inner view controllers

### ISSUE THREAD

**Issue by gerchicov-bp** [hemangshah/HHTabBarView#13]
For example create a view/view controller with table with a lot of items and try to scroll it to the bottom - the last cell is hidden by tab bar

**Comment by hemangshah** [comment]
Hi @gerchicov-bp I believe, this isn't an issue of `HHTabBarView`. It's because of your table's bottom constraint.

**Comment by hemangshah** [comment]
Hi @gerchicov-bp , I have updated the codebase for swift 4.2 and added a table in Locations tab (in Example) to show case that how to fix this overlap issue. FYR, I am also adding two screenshots here to let you know how to fix it by your self. If you still need help just comment here and I would be happy to help.

**How to activate Safe Area Layout Guide for a view controller** (Note: With latest Xcode and new project, this is by default).

<img width="1166" alt="1" src="https://user-images.githubusercontent.com/3313412/50040670-20e82c80-006e-11e9-9858-c0173393866f.png">

**Setting/Updating Constraints for the TableView as much the screenshot**:

<img width="1164" alt="2" src="https://user-images.githubusercontent.com/3313412/50040671-2180c300-006e-11e9-8941-aa8523cfab38.png">
